spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.cassandra.CassandraRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false
    admin:
      fail-fast: false

  mail:
    host: localhost
    port: 1025

app:
  jwt:
    secret: test-jwt-secret-for-medibook-integration-testing-secure-key-256bits
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
  phi:
    encryption-key: medibook-phi-aes256-encryption-key!

logging:
  level:
    com.medibook: DEBUG