spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:medibook}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:medibook}
    password: ${DB_PASSWORD:medibook}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    cassandra:
      contact-points: ${CASSANDRA_HOST:localhost}
      port: ${CASSANDRA_PORT:9042}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}  # MailHog for local dev

logging:
  level:
    com.medibook: DEBUG
    org.springframework.security: DEBUG
