---
apiVersion: v1
kind: ConfigMap
metadata:
  name: medibook-config
  namespace: medibook
data:
  redis-host: "medibook-redis-master"
  kafka-brokers: "medibook-kafka:9092"
  cassandra-host: "medibook-cassandra"
  cassandra-keyspace: "medibook"
  cassandra-datacenter: "datacenter1"
  cors-origins: "https://app.dreammedibook.com,https://app.medibook.com"
  frontend-url: "https://app.dreammedibook.com"
  otel-endpoint: "http://otel-collector:4318/v1/traces"
  tracing-sampling-probability: "0.10"
  time-zone: "Africa/Lagos"
