-- ─────────────────────────────────────────────────────────────────────────────
-- Migration V25: Avatar Storage Optimization — Move from Base64 to S3/MinIO
--
-- Purpose:
-- - Reduce user row size from ~2.7 MB to ~500 bytes
-- - Eliminate bloated table scans and improve query performance
-- - Enable CDN distribution and caching (CloudFront, Cloudflare)
-- - Separate concerns: app handles logic, storage handles files
--
-- Implementation Strategy:
-- - The existing avatar_url column will be reused for both old base64 URIs and new S3 URLs
-- - New avatars uploaded via StorageService will store S3 URLs directly
-- - Old base64 avatars remain functional until users re-upload (lazy migration)
-- - UserService.uploadAvatar() handles both formats transparently
--
-- Column Behavior:
-- - Avatar_url supports both formats seamlessly:
--   OLD: data:image/jpeg;base64,/9j/4AAQSkZJRgABA... (2-3 MB for base64)
--   NEW: https://s3.amazonaws.com/medibook-avatars/user-123/avatar.jpg (500 bytes)
--
-- No schema changes required:
-- - The MEDIUMTEXT column can store both formats
-- - New uploads via StorageService will use S3 URLs
-- - No data migration script needed (lazy migration approach)
--
-- Future Cleanup (when all users have migrated):
-- - Modify column type from MEDIUMTEXT to VARCHAR(500) for storage optimization
-- - Remove any remaining base64 URIs via scheduled cleanup task
-- ─────────────────────────────────────────────────────────────────────────────

-- Add index for avatar lookups (improves queries filtering by avatar_url presence)
CREATE INDEX idx_user_avatar_url ON users(avatar_url(100));

-- Add metadata comment for documentation
-- ALTER TABLE user MODIFY COLUMN avatar_url MEDIUMTEXT COMMENT 'Avatar URL: S3/MinIO URL or legacy base64 data URI';
