package com.medibook.ai.support.provider;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Claude (Anthropic) support assistant provider. Powers the in-app support chatbot that
 * helps users navigate MediBook (booking, cancellations, account questions).
 *
 * Active when: app.ai.support.provider=claude-api
 * Requires:    app.intelligence.claude-api.key (env: CLAUDE_API_KEY)
 *
 * Unlike the stub provider, every reply is generated by the model, so identical-looking
 * canned responses go away.
 */
@Slf4j
@Component
@ConditionalOnProperty(name = "app.ai.support.provider", havingValue = "claude-api")
public class ClaudeSupportProvider implements SupportAiProvider {

    private static final String API_URL       = "https://api.anthropic.com/v1/messages";
    // Use a real, generally-available Anthropic model id. The previous value
    // ("claude-haiku-4-5-20251001") was not an Anthropic-released model id, so
    // every request returned 400/404 from the API and the catch block fell
    // through to FALLBACK_REPLY ("I'm temporarily unable to reach the
    // assistant…"). Override at runtime via app.ai.support.claude-model if
    // a newer model is preferred without redeploying.
    private static final String DEFAULT_MODEL = "claude-3-5-haiku-20241022";
    private static final String ANTHROPIC_VER = "2023-06-01";
    private static final String FALLBACK_REPLY =
            "I'm temporarily unable to reach the assistant. Please try again in a moment.";

    @Value("${app.intelligence.claude-api.key:#{null}}")
    private String apiKey;

    @Value("${app.ai.support.max-tokens:512}")
    private int maxTokens;

    /** Override the Claude model id without touching code — e.g. when a new Haiku ships. */
    @Value("${app.ai.support.claude-model:claude-3-5-haiku-20241022}")
    private String model;

    private final ObjectMapper objectMapper;

    public ClaudeSupportProvider(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Override
    public String providerId() { return "claude-api"; }

    @Override
    public String generate(String systemPrompt, String userMessage) {
        return generate(systemPrompt, List.of(), userMessage);
    }

    @Override
    @CircuitBreaker(name = "supportAiProvider", fallbackMethod = "fallback")
    public String generate(String systemPrompt, List<Map<String, String>> conversationHistory, String userMessage) {
        if (apiKey == null || apiKey.isBlank()) {
            log.warn("ClaudeSupportProvider: CLAUDE_API_KEY not set — returning fallback");
            return FALLBACK_REPLY;
        }

        // Anthropic /v1/messages takes a `messages` array of {role, content} where role is
        // user|assistant. Replay history so the bot has conversation continuity, then append
        // the current user turn.
        List<Map<String, String>> messages = new ArrayList<>();
        if (conversationHistory != null) {
            for (Map<String, String> turn : conversationHistory) {
                String role    = turn.getOrDefault("role", "user");
                String content = turn.getOrDefault("content", "");
                if (content.isBlank()) continue;
                String mapped = role.equalsIgnoreCase("assistant")
                        || role.equalsIgnoreCase("ai")
                        || role.equalsIgnoreCase("bot")
                        ? "assistant" : "user";
                messages.add(Map.of("role", mapped, "content", content));
            }
        }
        messages.add(Map.of("role", "user", "content", userMessage));

        String resolvedModel = model != null && !model.isBlank() ? model : DEFAULT_MODEL;
        try {
            String body = objectMapper.writeValueAsString(Map.of(
                    "model",      resolvedModel,
                    "max_tokens", maxTokens,
                    "system",     systemPrompt,
                    "messages",   messages
            ));

            String raw = RestClient.builder()
                    .baseUrl(API_URL)
                    .defaultHeader("x-api-key", apiKey)
                    .defaultHeader("anthropic-version", ANTHROPIC_VER)
                    .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                    .build()
                    .post()
                    .body(body)
                    .retrieve()
                    .body(String.class);

            JsonNode root = objectMapper.readTree(raw);
            String text   = root.path("content").get(0).path("text").asText("");
            return text.isBlank() ? FALLBACK_REPLY : text;

        } catch (RestClientResponseException ex) {
            // Surface the actual Anthropic error body — "model not found", auth
            // failures, etc. otherwise stay hidden behind a generic message.
            log.error("ClaudeSupportProvider HTTP {} from Anthropic (model={}, keyPrefix={}): {}",
                    ex.getStatusCode(),
                    resolvedModel,
                    apiKey.length() > 12 ? apiKey.substring(0, 12) + "…" : "<short>",
                    ex.getResponseBodyAsString());
            return FALLBACK_REPLY;
        } catch (Exception ex) {
            log.error("ClaudeSupportProvider error (model={}): {}", resolvedModel, ex.getMessage(), ex);
            return FALLBACK_REPLY;
        }
    }

    @SuppressWarnings("unused")
    public String fallback(String systemPrompt, List<Map<String, String>> history, String userMessage, Throwable t) {
        log.warn("CircuitBreaker OPEN for Claude support provider: {}", t.getMessage());
        return FALLBACK_REPLY;
    }
}
